version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - python --version
  pre_build:
    commands:
      - >-
        ls -las
      - chmod +x *.sh
      - ./update-taskcat.sh $PIPELINE_BUCKET
  build:
    commands:
      - echo In buildspec-setup.yml Build started on `date`
      - >-
        zip -r doea-ec2-examples.zip ./samples/ec2 -j -x '*.git*'
      - >-
        zip -r doea-beanstalk-examples.zip ./samples/beanstalk -j -x '*.git*'
      - >-
        aws s3 sync . s3://$PIPELINE_BUCKET
  post_build:
    commands:
      - echo In buildspec-setup.yml Build completed on `date`
artifacts:
  files:
    - '**/*'
